### ISSUE TITLE
Why don't the info windows function?

### ISSUE THREAD

**Issue by 1stevengrant** [algolia/demo-geo-search#1]
If you click on a marker, I'd expect to see its info.

**Comment by kokliKo** [comment]
Hey @stevieg83 thanks for the issue.

You're right, on a real-life implementation I'd definitely add that.
This demo/code is mainly intented to show how to use Algolia's geo-search capabilities. People may implement geo-search using other libraries than Google Map, so we wanted to make the code related to GMap as short as possible.

Do you think that makes sense?

**Comment by 1stevengrant** [comment]
sure - no worries
